- name: Setup basic tools
  hosts: all
  tasks:

  - name: NTP Install
    become: true
    yum:
      name: ntp
      state: present
    register: ntp_installed

  - name: NTP Enable and start service
    become: true
    service:
      enabled: yes
      name: ntpd
      state: started
    when: ntp_installed is succeeded
    
  - name: NTP set timezone
    become: true
    file:
      src: /usr/share/zoneinfo/Europe/Kiev
      dest: /etc/localtime
      owner: root
      group: root
      mode: 0666
      state: link
      force: yes
    when: ntp_installed is succeeded
  
  - name: EPEL repo - Install.
    become: true
    package:
       name={{item}} 
       state=present
    with_items:
      - epel-release
    register: epel_installed

  - name: Basic tools - Install.
    become: true
    package:
       name={{item}}
       state=present
    with_items:
      - vim
      - nano
      - mc
      - wget
      - htop
      - net-tools
    when: epel_installed is succeeded

